sudo: required

services:
        - docker

language: python

python:
        - "3.5"

script:
        - python -m pytest -v tests/

after_success:
        - sh .travis/deploy_dockerhub.sh
        - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
